# Data configuration
data:
  local_dir: /content/data/pets

    
dataset:
  train_split: 0.7
  val_split: 0.3
  random_seed: 42
  num_classes: 37

# Training configuration
training:
  epochs: 10
  batch_size: 32
  optimizer:
    name: AdamW
    lr: 0.0001
  loss: CrossEntropyLoss
  metrics:
    - accuracy
    - f1_score

# Model configuration
model:
  name: resnet50
  pretrained: True
  num_classes: 37
  freeze_base: False

# Logging configuration
logging:
  level: INFO
  file: /content/logs/training.log
  format: '%(asctime)s - %(levelname)s - %(message)s'

# Artifacts configuration
artifacts:
  output_dir: /content/artifacts
  save_best_model: True
  save_logs: True
  save_metrics: True
